/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SpecialtyBreadsRouteImport } from './routes/specialty-breads'
import { Route as SourdoughBreadsRouteImport } from './routes/sourdough-breads'
import { Route as SnackBoxesRouteImport } from './routes/snack-boxes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeasonalSpecialRouteImport } from './routes/seasonal-special'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanEventRouteImport } from './routes/plan-event'
import { Route as OtherBakesRouteImport } from './routes/other-bakes'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as GrazingTablesRouteImport } from './routes/grazing-tables'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FoodHampersRouteImport } from './routes/food-hampers'
import { Route as FestiveRouteImport } from './routes/festive'
import { Route as DipsRouteImport } from './routes/dips'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as CakesRouteImport } from './routes/cakes'
import { Route as BuildHamperRouteImport } from './routes/build-hamper'
import { Route as BreadsRouteImport } from './routes/breads'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtyBreadsRoute = SpecialtyBreadsRouteImport.update({
  id: '/specialty-breads',
  path: '/specialty-breads',
  getParentRoute: () => rootRouteImport,
} as any)
const SourdoughBreadsRoute = SourdoughBreadsRouteImport.update({
  id: '/sourdough-breads',
  path: '/sourdough-breads',
  getParentRoute: () => rootRouteImport,
} as any)
const SnackBoxesRoute = SnackBoxesRouteImport.update({
  id: '/snack-boxes',
  path: '/snack-boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonalSpecialRoute = SeasonalSpecialRouteImport.update({
  id: '/seasonal-special',
  path: '/seasonal-special',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanEventRoute = PlanEventRouteImport.update({
  id: '/plan-event',
  path: '/plan-event',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherBakesRoute = OtherBakesRouteImport.update({
  id: '/other-bakes',
  path: '/other-bakes',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GrazingTablesRoute = GrazingTablesRouteImport.update({
  id: '/grazing-tables',
  path: '/grazing-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodHampersRoute = FoodHampersRouteImport.update({
  id: '/food-hampers',
  path: '/food-hampers',
  getParentRoute: () => rootRouteImport,
} as any)
const FestiveRoute = FestiveRouteImport.update({
  id: '/festive',
  path: '/festive',
  getParentRoute: () => rootRouteImport,
} as any)
const DipsRoute = DipsRouteImport.update({
  id: '/dips',
  path: '/dips',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CakesRoute = CakesRouteImport.update({
  id: '/cakes',
  path: '/cakes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildHamperRoute = BuildHamperRouteImport.update({
  id: '/build-hamper',
  path: '/build-hamper',
  getParentRoute: () => rootRouteImport,
} as any)
const BreadsRoute = BreadsRouteImport.update({
  id: '/breads',
  path: '/breads',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/breads': typeof BreadsRoute
  '/build-hamper': typeof BuildHamperRoute
  '/cakes': typeof CakesRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/dips': typeof DipsRoute
  '/festive': typeof FestiveRoute
  '/food-hampers': typeof FoodHampersRoute
  '/gallery': typeof GalleryRoute
  '/grazing-tables': typeof GrazingTablesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/other-bakes': typeof OtherBakesRoute
  '/plan-event': typeof PlanEventRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seasonal-special': typeof SeasonalSpecialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snack-boxes': typeof SnackBoxesRoute
  '/sourdough-breads': typeof SourdoughBreadsRoute
  '/specialty-breads': typeof SpecialtyBreadsRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/breads': typeof BreadsRoute
  '/build-hamper': typeof BuildHamperRoute
  '/cakes': typeof CakesRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/dips': typeof DipsRoute
  '/festive': typeof FestiveRoute
  '/food-hampers': typeof FoodHampersRoute
  '/gallery': typeof GalleryRoute
  '/grazing-tables': typeof GrazingTablesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/other-bakes': typeof OtherBakesRoute
  '/plan-event': typeof PlanEventRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seasonal-special': typeof SeasonalSpecialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snack-boxes': typeof SnackBoxesRoute
  '/sourdough-breads': typeof SourdoughBreadsRoute
  '/specialty-breads': typeof SpecialtyBreadsRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/breads': typeof BreadsRoute
  '/build-hamper': typeof BuildHamperRoute
  '/cakes': typeof CakesRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/dips': typeof DipsRoute
  '/festive': typeof FestiveRoute
  '/food-hampers': typeof FoodHampersRoute
  '/gallery': typeof GalleryRoute
  '/grazing-tables': typeof GrazingTablesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/other-bakes': typeof OtherBakesRoute
  '/plan-event': typeof PlanEventRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seasonal-special': typeof SeasonalSpecialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snack-boxes': typeof SnackBoxesRoute
  '/sourdough-breads': typeof SourdoughBreadsRoute
  '/specialty-breads': typeof SpecialtyBreadsRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/breads'
    | '/build-hamper'
    | '/cakes'
    | '/catering'
    | '/contact'
    | '/delivery'
    | '/dips'
    | '/festive'
    | '/food-hampers'
    | '/gallery'
    | '/grazing-tables'
    | '/llms.txt'
    | '/other-bakes'
    | '/plan-event'
    | '/privacy'
    | '/products'
    | '/refund'
    | '/reviews'
    | '/robots.txt'
    | '/seasonal-special'
    | '/sitemap.xml'
    | '/snack-boxes'
    | '/sourdough-breads'
    | '/specialty-breads'
    | '/terms'
    | '/workshops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/breads'
    | '/build-hamper'
    | '/cakes'
    | '/catering'
    | '/contact'
    | '/delivery'
    | '/dips'
    | '/festive'
    | '/food-hampers'
    | '/gallery'
    | '/grazing-tables'
    | '/llms.txt'
    | '/other-bakes'
    | '/plan-event'
    | '/privacy'
    | '/products'
    | '/refund'
    | '/reviews'
    | '/robots.txt'
    | '/seasonal-special'
    | '/sitemap.xml'
    | '/snack-boxes'
    | '/sourdough-breads'
    | '/specialty-breads'
    | '/terms'
    | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/breads'
    | '/build-hamper'
    | '/cakes'
    | '/catering'
    | '/contact'
    | '/delivery'
    | '/dips'
    | '/festive'
    | '/food-hampers'
    | '/gallery'
    | '/grazing-tables'
    | '/llms.txt'
    | '/other-bakes'
    | '/plan-event'
    | '/privacy'
    | '/products'
    | '/refund'
    | '/reviews'
    | '/robots.txt'
    | '/seasonal-special'
    | '/sitemap.xml'
    | '/snack-boxes'
    | '/sourdough-breads'
    | '/specialty-breads'
    | '/terms'
    | '/workshops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BreadsRoute: typeof BreadsRoute
  BuildHamperRoute: typeof BuildHamperRoute
  CakesRoute: typeof CakesRoute
  CateringRoute: typeof CateringRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  DipsRoute: typeof DipsRoute
  FestiveRoute: typeof FestiveRoute
  FoodHampersRoute: typeof FoodHampersRoute
  GalleryRoute: typeof GalleryRoute
  GrazingTablesRoute: typeof GrazingTablesRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OtherBakesRoute: typeof OtherBakesRoute
  PlanEventRoute: typeof PlanEventRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RefundRoute: typeof RefundRoute
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SeasonalSpecialRoute: typeof SeasonalSpecialRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SnackBoxesRoute: typeof SnackBoxesRoute
  SourdoughBreadsRoute: typeof SourdoughBreadsRoute
  SpecialtyBreadsRoute: typeof SpecialtyBreadsRoute
  TermsRoute: typeof TermsRoute
  WorkshopsRoute: typeof WorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialty-breads': {
      id: '/specialty-breads'
      path: '/specialty-breads'
      fullPath: '/specialty-breads'
      preLoaderRoute: typeof SpecialtyBreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourdough-breads': {
      id: '/sourdough-breads'
      path: '/sourdough-breads'
      fullPath: '/sourdough-breads'
      preLoaderRoute: typeof SourdoughBreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snack-boxes': {
      id: '/snack-boxes'
      path: '/snack-boxes'
      fullPath: '/snack-boxes'
      preLoaderRoute: typeof SnackBoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasonal-special': {
      id: '/seasonal-special'
      path: '/seasonal-special'
      fullPath: '/seasonal-special'
      preLoaderRoute: typeof SeasonalSpecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-event': {
      id: '/plan-event'
      path: '/plan-event'
      fullPath: '/plan-event'
      preLoaderRoute: typeof PlanEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-bakes': {
      id: '/other-bakes'
      path: '/other-bakes'
      fullPath: '/other-bakes'
      preLoaderRoute: typeof OtherBakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grazing-tables': {
      id: '/grazing-tables'
      path: '/grazing-tables'
      fullPath: '/grazing-tables'
      preLoaderRoute: typeof GrazingTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-hampers': {
      id: '/food-hampers'
      path: '/food-hampers'
      fullPath: '/food-hampers'
      preLoaderRoute: typeof FoodHampersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festive': {
      id: '/festive'
      path: '/festive'
      fullPath: '/festive'
      preLoaderRoute: typeof FestiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dips': {
      id: '/dips'
      path: '/dips'
      fullPath: '/dips'
      preLoaderRoute: typeof DipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cakes': {
      id: '/cakes'
      path: '/cakes'
      fullPath: '/cakes'
      preLoaderRoute: typeof CakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-hamper': {
      id: '/build-hamper'
      path: '/build-hamper'
      fullPath: '/build-hamper'
      preLoaderRoute: typeof BuildHamperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breads': {
      id: '/breads'
      path: '/breads'
      fullPath: '/breads'
      preLoaderRoute: typeof BreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BreadsRoute: BreadsRoute,
  BuildHamperRoute: BuildHamperRoute,
  CakesRoute: CakesRoute,
  CateringRoute: CateringRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  DipsRoute: DipsRoute,
  FestiveRoute: FestiveRoute,
  FoodHampersRoute: FoodHampersRoute,
  GalleryRoute: GalleryRoute,
  GrazingTablesRoute: GrazingTablesRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OtherBakesRoute: OtherBakesRoute,
  PlanEventRoute: PlanEventRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RefundRoute: RefundRoute,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SeasonalSpecialRoute: SeasonalSpecialRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SnackBoxesRoute: SnackBoxesRoute,
  SourdoughBreadsRoute: SourdoughBreadsRoute,
  SpecialtyBreadsRoute: SpecialtyBreadsRoute,
  TermsRoute: TermsRoute,
  WorkshopsRoute: WorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
